default_platform(:ios)

platform :ios do
  desc "Build iOS app for App Store"
  lane :release do
    setup_ci if ENV['CI']

    # Update code signing settings
    update_code_signing_settings(
      use_automatic_signing: true,
      path: "./ios/BillsTracker.xcodeproj",
      team_id: "824F44HKCD"
    )

    # Build the app
    build_app(
      workspace: "./ios/BillsTracker.xcworkspace",
      scheme: "BillsTracker",
      export_method: "app-store",
      output_directory: "./build",
      output_name: "BillsTracker.ipa",
      clean: true,
      xcargs: "-allowProvisioningUpdates",
      export_team_id: "824F44HKCD"
    )
  end
end
